language: ruby
env:
  - CPLUS_INCLUDE_PATH=/usr/include/atlas C_INCLUDE_PATH=/usr/include/atlas
rvm:
  - "1.9.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-base-dev
script: bundle exec rake compile && bundle exec rake spec

